theme: jekyll-theme-slate
title: Welcome to Sharon Byegon's Portfolio
description: My projects at the Gearbox Academy.
decription: Feel free to keep to bookmark this to keep an eye on my project updates.
